"""
R1 tests for assert_queue_alignment: T12.

FR-19/FR-20/FR-21 — assert_queue_alignment detects a queue-NN.json deliberately
desynced from queues-manifest.json / expectations.json and raises; campaign.py
run aborts before starting any server when it raises; build_queues.py and
hydrate.py carry the "always run in sequence" comment.

The negative-path test operates on a COPY of the fixture under a temp
directory, never on the real gitignored inputs/queue-NN.json (those are
regenerated by hydrate.py --mode queues and may be absent on a clean
checkout without the local CSV).
"""
import json
import shutil
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tests"))

from runner.runner import assert_queue_alignment, FIXTURES_DIR

FIXTURE_ID = "w2-branching/support-intake"
REAL_FIXTURE_DIR = FIXTURES_DIR / FIXTURE_ID


def _hydrated() -> bool:
    return any((REAL_FIXTURE_DIR / "inputs").glob("queue-*.json"))


def _copy_fixture(tmp_path: Path) -> Path:
    dest = tmp_path / "support-intake"
    shutil.copytree(REAL_FIXTURE_DIR, dest, ignore=shutil.ignore_patterns("__pycache__"))
    return dest


@pytest.mark.skipif(not _hydrated(), reason="queue-*.json not hydrated locally")
def test_aligned_fixture_passes():
    assert_queue_alignment(REAL_FIXTURE_DIR) is None


@pytest.mark.skipif(not _hydrated(), reason="queue-*.json not hydrated locally")
def test_desynced_queue_raises(tmp_path):
    fixture_dir = _copy_fixture(tmp_path)
    queue_path = fixture_dir / "inputs" / "queue-01.json"
    data = json.loads(queue_path.read_text(encoding="utf-8"))
    data["queue"][0], data["queue"][1] = data["queue"][1], data["queue"][0]
    queue_path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")

    with pytest.raises(RuntimeError, match="queue-01"):
        assert_queue_alignment(fixture_dir)


@pytest.mark.skipif(not _hydrated(), reason="queue-*.json not hydrated locally")
def test_desynced_queue_length_raises(tmp_path):
    fixture_dir = _copy_fixture(tmp_path)
    queue_path = fixture_dir / "inputs" / "queue-01.json"
    data = json.loads(queue_path.read_text(encoding="utf-8"))
    data["queue"].pop()
    queue_path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")

    with pytest.raises(RuntimeError, match="queue-01"):
        assert_queue_alignment(fixture_dir)


def test_campaign_run_aborts_before_server_on_misaligned_queue(monkeypatch):
    import runner.campaign as campaign_mod

    def boom(fixture_dir):
        raise RuntimeError("queue-01: staged input diverges from queues-manifest.json at index 0")
    monkeypatch.setattr(campaign_mod, "assert_queue_alignment", boom)

    started = []
    monkeypatch.setattr(campaign_mod, "_start_server", lambda cell: started.append(True))

    with pytest.raises(SystemExit):
        campaign_mod.cmd_run(None)

    assert started == []


def test_build_queues_and_hydrate_carry_sequencing_comment():
    build_queues_src = (REPO_ROOT / "tests" / "scripts" / "build_queues.py").read_text(encoding="utf-8")
    hydrate_src = (REPO_ROOT / "tests" / "scripts" / "hydrate.py").read_text(encoding="utf-8")
    for src in (build_queues_src, hydrate_src):
        assert "hydrate.py --mode queues" in src
        assert "assert_queue_alignment" in src
