"""
R1 tests for campaign.py: T06, T08, T09, T10, T11.

All server/network interaction is monkeypatched -- these are pure control-flow
tests over campaign.py's plan/reconcile/ladder/cell-lifecycle logic, no GPU,
no llama-server, no live model calls.

T06 (FR-10,FR-11) — plan reads campaign-cells.json: 5 cells, values match the
    frozen table in tests/modes.json.
T08 (FR-14) — rows already 'done' in index.jsonl are marked done in a
    regenerated plan without rerunning.
T09 (FR-15,FR-17) — cell lifecycle: acceptance failure skips all pending rows
    of the cell (no run spent) and moves on; acceptance pass iterates every
    (mode, queue); server always stopped, even on exception.
T10 — full grid: _run_rows executes all five levels of a terna even
    when L0 scores 0.99, and the adaptive surface is gone from the module. The
    exact reverse of what T10 asserted before 2026-08-22.
T11 (FR-18) — resume: rows already 'done' (simulating a kill mid-cell) are
    never re-executed when the terna is walked again.
T12 — cell/mode/disk invariant: every cell's gguf agrees with the 'model' label
    of each of its modes in tests/modes.json (the frozen table lives
    there, tracked, not in the gitignored tests/env.json), and the weights file
    actually exists. Added after the gemma-4-12b typo (2026-08-20):
    campaign-cells.json named a Q4_K_M that was never downloaded, while the file
    on disk was the QAT Q4_K_L. Nothing failed at commit time -- the cell would
    have died at _start_server and its 150 rows would have been marked
    'skipped-acceptance', a status indistinguishable from a genuine hardware
    verdict.
T13 (FR-01,FR-02,FR-04) — the acceptance probe prefills a real-sized
    prompt; prompt_n below the minimum is reported as an INVALID measurement,
    not as a hardware verdict; the 1000 t/s threshold is untouched; and the
    protocol amendment is actually written in the protocol.
T14 (FR-12) — a plan whose every row was rejected by a previous run is
    refused instead of being silently walked as a no-op.
"""
import argparse
import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tests"))

import runner.campaign as campaign_mod


@pytest.fixture(autouse=True)
def _no_dashboard_subprocesses():
    """Never let a test regenerate a real dashboard.

    _run_rows calls _regen_dashboard after every row, and campaign.py's
    RESULTS_DIR is tests/results -- the pilot's tracked results -- until
    _use_results_root moves it. Driving _run_rows from a test therefore rewrote
    576 runs' worth of committed dashboard.html, assets/dashboard.js and
    index.csv, which stayed invisible only while the regenerated bytes happened
    to match the committed ones.

    Flipped through the flag --no-dashboard already sets, so the call path
    under test is the production one and only the subprocess is missing."""
    saved = campaign_mod._dashboard_enabled
    campaign_mod._dashboard_enabled = False
    yield
    campaign_mod._dashboard_enabled = saved


class _FakeFidelity:
    def __init__(self, rate):
        self.conditional_rate = rate


class _FakeScore:
    def __init__(self, rate):
        self.fidelity = _FakeFidelity(rate)


# ---------------------------------------------------------------------------
# T06 — campaign-cells.json matches the frozen table
# ---------------------------------------------------------------------------

def test_plan_reads_the_cells_matching_env_json():
    """Six cells over five ggufs: qwen3.5-9b appears twice because its two modes
    were split so the thinking one could run last (2026-08-23). The extra entry
    costs one more model load and changes nothing about what is measured."""
    cells = campaign_mod._load_cells()
    assert len(cells) == 6
    names = {c["cell"] for c in cells}
    assert names == {"qwen3.5-9b-nothink", "qwen3.5-9b-think", "ministral-3-8b",
                     "granite-4.1-8b", "gemma-4-12b", "phi4-mini"}
    assert len({c["gguf"] for c in cells}) == 5

    for cell in cells:
        assert cell["kv_cache_type"] == "q8_0"
        assert cell["n_parallel"] == 1

    by_name = {c["cell"]: c for c in cells}
    # ctx_size raised to each cell's measured VRAM ceiling on 2026-08-22 (
    # protocol SS12); the values themselves live in CTX_CEILING at T16.
    assert by_name["qwen3.5-9b-nothink"]["ctx_size"] == 51200
    assert by_name["qwen3.5-9b-nothink"]["modes"] == ["llama-qwen3.5-9b-nothink"]
    assert by_name["qwen3.5-9b-think"]["ctx_size"] == 51200
    assert by_name["qwen3.5-9b-think"]["modes"] == ["llama-qwen3.5-9b-think"]
    assert by_name["ministral-3-8b"]["ctx_size"] == 38912
    assert by_name["ministral-3-8b"]["modes"] == ["llama-ministral-8b"]
    assert by_name["granite-4.1-8b"]["ctx_size"] == 28672
    assert by_name["gemma-4-12b"]["ctx_size"] == 43008
    assert by_name["phi4-mini"]["ctx_size"] == 43008


def test_build_plan_enumerates_full_coordinate_space():
    cells = campaign_mod._load_cells()
    queue_ids = campaign_mod._load_queue_ids()
    assert len(queue_ids) == 10

    rows = campaign_mod.build_plan(cells, queue_ids)

    n_modes = sum(len(c["modes"]) for c in cells)
    expected = n_modes * len(campaign_mod.RENDERINGS) * len(queue_ids) * campaign_mod.REPS_PER_RENDERING
    assert len(rows) == expected
    assert all(r["status"] == "pending" for r in rows)


def test_build_plan_covers_all_seven_renderings():
    """SS5.1 + SS5.4: five collateral levels and two prose renderings, on ONE
    selector. A plan built over five would run the experiment without the
    comparison it was designed around, and nothing downstream would say so --
    the missing cells would simply never appear in the index."""
    rows = campaign_mod.build_plan(campaign_mod._load_cells(), campaign_mod._load_queue_ids())
    assert {r["rendering"] for r in rows} == set(campaign_mod.RENDERINGS)
    assert len(campaign_mod.RENDERINGS) == 7


# ---------------------------------------------------------------------------
# T08 — resume reconciliation against index.jsonl
# ---------------------------------------------------------------------------

def test_reconcile_marks_pending_rows_done_from_index(tmp_path, monkeypatch):
    monkeypatch.setattr(campaign_mod, "INDEX_PATH", tmp_path / "index.jsonl")
    monkeypatch.setattr(campaign_mod, "_mode_config", lambda mode: {
        "model": "model-x", "backend": "openai", "reasoning_budget": 0,
        "key": "", "url": "http://x", "temperature": 0.2, "thinking": None,
        "ctx_size": 1000, "kv_cache_type": "q8_0", "n_parallel": 1,
    })
    index_row = {
        "fixture_id": campaign_mod.SUPPORT_INTAKE_FIXTURE_ID,
        "staged_input_id": "queue-01", "context": "E0", "model_id": "model-x",
        "spec_version": campaign_mod.SPEC_VERSION, "backend": "openai",
        "reasoning_budget": 0, "process_rendering": "L1",
        # the coordinate carries the mode since 2026-08-23: without it two
        # modes on the same gguf credit each other's runs
        "mode": "m1",
        "status": "done",
    }
    (tmp_path / "index.jsonl").write_text(json.dumps(index_row) + "\n", encoding="utf-8")

    plan = [
        {"cell": "c1", "mode": "m1", "rendering": "L1", "queue": "queue-01", "rep": 1, "status": "pending"},
        {"cell": "c1", "mode": "m1", "rendering": "L1", "queue": "queue-01", "rep": 2, "status": "pending"},
        {"cell": "c1", "mode": "m1", "rendering": "L1", "queue": "queue-01", "rep": 3, "status": "pending"},
    ]
    campaign_mod._reconcile_with_index(plan)

    assert plan[0]["status"] == "done"
    assert plan[1]["status"] == "pending"
    assert plan[2]["status"] == "pending"


def test_reconcile_leaves_non_matching_rows_pending(tmp_path, monkeypatch):
    monkeypatch.setattr(campaign_mod, "INDEX_PATH", tmp_path / "index.jsonl")
    monkeypatch.setattr(campaign_mod, "_mode_config", lambda mode: {
        "model": "model-x", "backend": "openai", "reasoning_budget": 0,
        "key": "", "url": "http://x", "temperature": 0.2, "thinking": None,
        "ctx_size": 1000, "kv_cache_type": "q8_0", "n_parallel": 1,
    })
    (tmp_path / "index.jsonl").write_text("", encoding="utf-8")

    plan = [{"cell": "c1", "mode": "m1", "rendering": "L1", "queue": "queue-01", "rep": 1, "status": "pending"}]
    campaign_mod._reconcile_with_index(plan)
    assert plan[0]["status"] == "pending"


# ---------------------------------------------------------------------------
# T09 — cell lifecycle
# ---------------------------------------------------------------------------

def test_cell_acceptance_failure_skips_all_pending_no_run(monkeypatch, tmp_path):
    monkeypatch.setattr(campaign_mod, "_start_server", lambda cell: None)
    monkeypatch.setattr(campaign_mod, "_wait_for_server", lambda *a, **k: True)
    monkeypatch.setattr(campaign_mod, "_acceptance_check", lambda fixture_meta: False)
    stopped = []
    monkeypatch.setattr(campaign_mod, "_stop_server", lambda: stopped.append(True))
    ladder_calls = []
    monkeypatch.setattr(campaign_mod, "_run_rows", lambda *a, **k: ladder_calls.append(a))
    monkeypatch.setattr(campaign_mod, "_save_plan", lambda plan: None)

    cell = {"cell": "c1", "runner_type": "api", "gguf": "x.gguf", "ctx_size": 1000, "modes": ["m1"]}
    plan = [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "queue-01", "rep": 1, "status": "pending"}]
    campaign_mod._run_cell(cell, plan, tmp_path, {}, {}, {})

    assert plan[0]["status"] == "skipped-acceptance"
    assert ladder_calls == []
    assert stopped == [True]


def test_cell_acceptance_pass_iterates_every_mode_and_queue(monkeypatch, tmp_path):
    monkeypatch.setattr(campaign_mod, "_start_server", lambda cell: None)
    monkeypatch.setattr(campaign_mod, "_wait_for_server", lambda *a, **k: True)
    monkeypatch.setattr(campaign_mod, "_acceptance_check", lambda fixture_meta: True)
    stopped = []
    monkeypatch.setattr(campaign_mod, "_stop_server", lambda: stopped.append(True))
    ladder_calls = []
    monkeypatch.setattr(
        campaign_mod, "_run_rows",
        lambda cell, mode, queue_id, plan, *a, **k: ladder_calls.append((mode, queue_id)),
    )
    monkeypatch.setattr(campaign_mod, "_save_plan", lambda plan: None)

    cell = {"cell": "c1", "runner_type": "api", "gguf": "x.gguf", "ctx_size": 1000, "modes": ["m1", "m2"]}
    plan = [
        {"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "queue-01", "rep": 1, "status": "pending"},
        {"cell": "c1", "mode": "m2", "rendering": "L0", "queue": "queue-02", "rep": 1, "status": "pending"},
    ]
    campaign_mod._run_cell(cell, plan, tmp_path, {}, {}, {})

    assert set(ladder_calls) == {("m1", "queue-01"), ("m2", "queue-02")}
    assert stopped == [True]


def test_cell_no_pending_rows_skips_without_starting_server(monkeypatch, tmp_path):
    started = []
    monkeypatch.setattr(campaign_mod, "_start_server", lambda cell: started.append(True))
    stopped = []
    monkeypatch.setattr(campaign_mod, "_stop_server", lambda: stopped.append(True))

    cell = {"cell": "c1", "runner_type": "api", "gguf": "x.gguf", "ctx_size": 1000, "modes": ["m1"]}
    plan = [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "queue-01", "rep": 1, "status": "done"}]
    campaign_mod._run_cell(cell, plan, tmp_path, {}, {}, {})

    assert started == []
    assert stopped == []


def test_cell_server_stopped_even_on_exception(monkeypatch, tmp_path):
    monkeypatch.setattr(campaign_mod, "_start_server", lambda cell: None)
    monkeypatch.setattr(campaign_mod, "_wait_for_server", lambda *a, **k: True)

    def boom(fixture_meta):
        raise RuntimeError("boom")
    monkeypatch.setattr(campaign_mod, "_acceptance_check", boom)
    stopped = []
    monkeypatch.setattr(campaign_mod, "_stop_server", lambda: stopped.append(True))

    cell = {"cell": "c1", "runner_type": "api", "gguf": "x.gguf", "ctx_size": 1000, "modes": ["m1"]}
    plan = [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "queue-01", "rep": 1, "status": "pending"}]
    with pytest.raises(RuntimeError):
        campaign_mod._run_cell(cell, plan, tmp_path, {}, {}, {})

    assert stopped == [True]


# ---------------------------------------------------------------------------
# T10 — full grid: no early stop, no adaptive surface left
# ---------------------------------------------------------------------------

def _full_ladder_plan(cell="c1", mode="m1", queue="q1"):
    return [
        {"cell": cell, "mode": mode, "rendering": lvl, "queue": queue, "rep": rep, "status": "pending"}
        for lvl in campaign_mod.RENDERINGS for rep in (1, 2, 3)
    ]


def test_run_rows_executes_every_rendering_even_when_l0_scores_high(monkeypatch):
    """The reverse of the pre-2026-08-22 assertion. A cell that clears 0.99 at
    L0 must still be measured at every other rendering: whether fidelity stays
    above threshold as L grows -- and how prose compares (SS5.4) -- is the
    question, not the stopping rule."""
    calls = []

    def fake_execute_row(row, cell, mode, level, queue_id, *a, **k):
        calls.append((level, row["rep"]))
        row["status"] = "done"
        return _FakeScore(0.99 if level == "L0" else 0.0)

    monkeypatch.setattr(campaign_mod, "_execute_row", fake_execute_row)
    monkeypatch.setattr(campaign_mod, "_save_plan", lambda plan: None)

    plan = _full_ladder_plan()
    campaign_mod._run_rows({"cell": "c1"}, "m1", "q1", plan, None, {}, {}, {})

    assert [lvl for lvl, _rep in calls] == [lvl for lvl in campaign_mod.RENDERINGS for _ in (1, 2, 3)]
    assert len(calls) == 3 * len(campaign_mod.RENDERINGS) == 21
    assert all(r["status"] == "done" for r in plan)


def test_run_rows_saves_plan_after_every_single_run(monkeypatch):
    """FR-14 unchanged: an interruption never loses more than the run in flight."""
    saves = []

    def fake_execute_row(row, cell, mode, level, queue_id, *a, **k):
        row["status"] = "done"
        return _FakeScore(0.10)

    monkeypatch.setattr(campaign_mod, "_execute_row", fake_execute_row)
    monkeypatch.setattr(campaign_mod, "_save_plan", lambda plan: saves.append(len(
        [r for r in plan if r["status"] == "done"])))

    plan = _full_ladder_plan()
    campaign_mod._run_rows({"cell": "c1"}, "m1", "q1", plan, None, {}, {}, {})

    assert saves == list(range(1, 3 * len(campaign_mod.RENDERINGS) + 1))


def test_adaptive_surface_is_gone():
    """The ladder is not merely unused: it is absent. A dormant _run_ladder
    would be a second, silent execution semantics one call site away."""
    for name in ("_run_ladder", "_skip_higher_levels", "ACCEPTABILITY_THRESHOLD"):
        assert not hasattr(campaign_mod, name), f"{name} still exposed by campaign.py"

    source = (REPO_ROOT / "tests" / "runner" / "campaign.py").read_text(encoding="utf-8")
    assert "skipped-adaptive" not in source


# ---------------------------------------------------------------------------
# T11 — resume: already-done rows never re-executed
# ---------------------------------------------------------------------------

def test_run_rows_resume_skips_already_done_rows(monkeypatch):
    calls = []

    def fake_execute_row(row, cell, mode, level, queue_id, *a, **k):
        calls.append((level, row["rep"]))
        row["status"] = "done"
        return _FakeScore(0.10)

    monkeypatch.setattr(campaign_mod, "_execute_row", fake_execute_row)
    monkeypatch.setattr(campaign_mod, "_save_plan", lambda plan: None)

    plan = _full_ladder_plan()
    plan[0]["status"] = "done"  # (L0, rep=1) simulates a row completed before the kill

    campaign_mod._run_rows({"cell": "c1"}, "m1", "q1", plan, None, {}, {}, {})

    assert ("L0", 1) not in calls
    assert ("L0", 2) in calls
    assert ("L0", 3) in calls


# ---------------------------------------------------------------------------
# T12 — cell/mode/disk invariant
# ---------------------------------------------------------------------------

MODES_PATH = REPO_ROOT / "tests" / "modes.json"
AI_MODELS_DIR = campaign_mod.LLAMA_DIR / "ai-models"


def _modes_by_name(path):
    return {e["mode"]: e for e in json.loads(path.read_text(encoding="utf-8"))["modes"]}


def _assert_modes_match_cells(by_mode, origine):
    """Every mode of every cell must carry that cell's gguf and knobs.

    'model' is not cosmetic: campaign.py::_execute_row writes it as Config.model_id
    into every run record and into index.jsonl, and _reconcile_with_index uses it
    as the resume join key. A wrong value mislabels the provenance of the data.
    """
    for cell in campaign_mod._load_cells():
        for name in cell["modes"]:
            assert name in by_mode, f"{origine}: mode {name} (cell {cell['cell']}) assente"
            entry = by_mode[name]
            assert entry["model"] == "ai-models/" + cell["gguf"], (
                f"{origine}: {name} dichiara model={entry['model']!r}, "
                f"la cella {cell['cell']} usa gguf={cell['gguf']!r}"
            )
            for chiave in ("ctx_size", "kv_cache_type", "n_parallel"):
                assert entry[chiave] == cell[chiave], (
                    f"{origine}: {name} ha {chiave}={entry[chiave]!r}, "
                    f"la cella {cell['cell']} ha {cell[chiave]!r}"
                )


def test_modes_json_matches_cells():
    """tests/modes.json is what _load_mode_entry actually reads at runtime, and
    Tracking the configuration made it skipif-free: the check runs everywhere -- including the
    fresh clone where a typo like the gemma one could otherwise reappear
    unobserved. The copy it replaced (tests/campaign-modes.json) is gone with the
    divergence class it carried."""
    _assert_modes_match_cells(_modes_by_name(MODES_PATH), "modes.json")


@pytest.mark.skipif(not AI_MODELS_DIR.is_dir(), reason=f"weights dir not present on this machine")
def test_cell_gguf_files_exist_on_disk():
    """The check that would have caught the gemma typo. _start_server passes
    cell['gguf'] straight to llama-server's -m: a missing file means the server
    never comes up and the whole cell is silently skipped."""
    mancanti = [
        (cell["cell"], cell["gguf"])
        for cell in campaign_mod._load_cells()
        if not (AI_MODELS_DIR / cell["gguf"]).is_file()
    ]
    assert not mancanti, f"gguf dichiarati ma assenti in {AI_MODELS_DIR}: {mancanti}"


# ---------------------------------------------------------------------------
# T13 — acceptance probe (FR-01, FR-02) and the protocol amendment (FR-04)
# ---------------------------------------------------------------------------

FIXTURE_BODY = "Support intake fixture body. " * 40  # ~1,120 chars, repeated by the probe
PROBE_META = {"meta": {"system_prompt": "sys"}, "body": FIXTURE_BODY}


class _FakeResp:
    def __init__(self, payload):
        self._payload = json.dumps(payload).encode()

    def read(self):
        return self._payload

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


def _install_fake_server(monkeypatch, timings):
    """One urlopen for both calls _acceptance_check makes: /v1/models to read the
    model id, /v1/chat/completions to run the probe. The probe body sent is
    captured so the size assertions can look at what actually went on the wire."""
    sent = {}

    def fake_urlopen(req, *a, **k):
        url = req if isinstance(req, str) else req.full_url
        if url.endswith("/v1/models"):
            return _FakeResp({"data": [{"id": "model-x"}]})
        sent["payload"] = json.loads(req.data.decode())
        return _FakeResp({"choices": [{"message": {"content": "ready"}}], "timings": timings})

    monkeypatch.setattr(campaign_mod.urllib.request, "urlopen", fake_urlopen)
    monkeypatch.setattr(campaign_mod, "_vram", lambda: (1000, 2000))
    return sent


def test_probe_prompt_reaches_campaign_sized_prefill():
    """The non-regression test the card asks for (1.3): it fails if the probe
    ever goes back to measuring the fixed overhead of a short request."""
    prompt = campaign_mod._acceptance_probe_prompt(PROBE_META)
    assert len(prompt) >= campaign_mod.PROBE_MIN_PROMPT_CHARS
    assert prompt.count(FIXTURE_BODY) > 1
    assert campaign_mod.PROBE_MIN_PROMPT_CHARS >= 15000


def test_probe_prompt_refuses_an_empty_fixture_body():
    with pytest.raises(RuntimeError):
        campaign_mod._acceptance_probe_prompt({"meta": {}, "body": "   "})


def test_acceptance_sends_the_full_sized_probe(monkeypatch):
    sent = _install_fake_server(monkeypatch, {"prompt_n": 4000, "prompt_per_second": 1900.0})
    assert campaign_mod._acceptance_check(PROBE_META) is True

    user_msg = [m for m in sent["payload"]["messages"] if m["role"] == "user"][0]
    assert len(user_msg["content"]) >= campaign_mod.PROBE_MIN_PROMPT_CHARS
    assert sent["payload"]["max_tokens"] == campaign_mod.ACCEPTANCE_MAX_TOKENS


def test_acceptance_rejects_an_invalid_measurement_explicitly(monkeypatch, capsys):
    """18 tokens at 5000 t/s is not a fast cell: it is no measurement at all.
    This is the 2026-08-22 failure mode, and it must say so."""
    _install_fake_server(monkeypatch, {"prompt_n": 18, "prompt_per_second": 5000.0})
    assert campaign_mod._acceptance_check(PROBE_META) is False

    out = capsys.readouterr().out
    assert "INVALID" in out
    assert "prompt_n=18" in out
    assert str(campaign_mod.PROBE_MIN_PROMPT_TOKENS) in out


def test_acceptance_rejects_a_genuinely_slow_cell(monkeypatch, capsys):
    _install_fake_server(monkeypatch, {"prompt_n": 4000, "prompt_per_second": 300.0})
    assert campaign_mod._acceptance_check(PROBE_META) is False

    out = capsys.readouterr().out
    assert "INVALID" not in out  # a hardware verdict, and distinguishable from one
    assert "prompt_n=4000" in out


def test_prefill_threshold_is_unchanged():
    """The full grid changes the input the criterion is measured on, never its value."""
    assert campaign_mod.PREFILL_TPS_THRESHOLD == 1000


PROTOCOL_PATH = REPO_ROOT / "doc" / "experiment-minimum-context.md"


def test_protocol_records_the_full_grid_amendment():
    """A formal requirement, not a nicety: the adaptive ladder is part of the
    pre-registered protocol, so withdrawing it is an amendment (SS12). Code
    review cannot catch a missing one -- nothing in the driver points at it."""
    text = PROTOCOL_PATH.read_text(encoding="utf-8")
    amendments = text.split("## 12. Amendments", 1)[1]
    rows = [ln for ln in amendments.splitlines() if ln.startswith("| 2026-08-22")]
    assert rows, "no 2026-08-22 amendment row in SS12"
    assert any("grid" in r.lower() for r in rows)

    section = text.split("### 7.3", 1)[1].split("### 7.4", 1)[0]
    assert "2026-08-22" in section
    assert "exhaustively" in section

    # The old rule may still appear, but only as history: the section quotes what
    # it replaced, and that quote must stay inside the italicised amendment note.
    historical = section.split("*", 2)[1] if section.count("*") >= 2 else ""
    assert "stop as soon as" not in section.replace(historical, "")


# ---------------------------------------------------------------------------
# T14 — a plan every row of which was rejected is refused, not silently walked
# ---------------------------------------------------------------------------

def test_run_refuses_a_plan_with_no_pending_and_rejected_rows():
    plan = [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "q1", "rep": r,
             "status": "skipped-acceptance"} for r in (1, 2, 3)]
    plan[0]["status"] = "done"

    with pytest.raises(SystemExit) as exc:
        campaign_mod._assert_plan_is_runnable(plan)
    msg = str(exc.value)
    assert "0 pending" in msg
    assert "campaign.py plan" in msg


def test_run_accepts_an_exhausted_plan_without_complaining(monkeypatch):
    monkeypatch.setattr(campaign_mod, "_load_cells", lambda path=None: [{"cell": "c1"}])
    plan = [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "q1", "rep": r,
             "status": "done"} for r in (1, 2, 3)]
    campaign_mod._assert_plan_is_runnable(plan)  # no exit: legitimately finished


def test_run_accepts_a_plan_with_pending_rows(monkeypatch):
    monkeypatch.setattr(campaign_mod, "_load_cells", lambda path=None: [{"cell": "c1"}])
    plan = [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "q1", "rep": 1,
             "status": "pending"},
            {"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "q1", "rep": 2,
             "status": "skipped-acceptance"}]
    campaign_mod._assert_plan_is_runnable(plan)


# ---------------------------------------------------------------------------
# T15 (FR-13) — resume does not double-count index entries
# ---------------------------------------------------------------------------

def _install_fake_mode(monkeypatch, tmp_path):
    monkeypatch.setattr(campaign_mod, "INDEX_PATH", tmp_path / "index.jsonl")
    monkeypatch.setattr(campaign_mod, "_mode_config", lambda mode: {
        "model": "model-x", "backend": "openai", "reasoning_budget": 0,
        "key": "", "url": "http://x", "temperature": 0.2, "thinking": None,
        "ctx_size": 1000, "kv_cache_type": "q8_0", "n_parallel": 1,
    })


def _write_index(tmp_path, n):
    row = {
        "fixture_id": campaign_mod.SUPPORT_INTAKE_FIXTURE_ID,
        "staged_input_id": "queue-01", "context": "E0", "model_id": "model-x",
        "spec_version": campaign_mod.SPEC_VERSION, "backend": "openai",
        "reasoning_budget": 0, "process_rendering": "L1",
        # the coordinate carries the mode since 2026-08-23: without it two
        # modes on the same gguf credit each other's runs
        "mode": "m1",
        "status": "done",
    }
    (tmp_path / "index.jsonl").write_text(
        "".join(json.dumps(row) + "\n" for _ in range(n)), encoding="utf-8")


def _three_reps(status_of_rep1="pending"):
    return [
        {"cell": "c1", "mode": "m1", "rendering": "L1", "queue": "queue-01", "rep": rep,
         "status": status_of_rep1 if rep == 1 else "pending"}
        for rep in (1, 2, 3)
    ]


def test_resume_does_not_credit_an_already_counted_index_entry(tmp_path, monkeypatch):
    """The 2026-08-22 kill mid-smoke exposed this: rep=1 is done in the plan AND
    has its index entry. Crediting that entry again would mark rep=2 done without
    ever running it."""
    _install_fake_mode(monkeypatch, tmp_path)
    _write_index(tmp_path, 1)

    plan = _three_reps(status_of_rep1="done")
    campaign_mod._reconcile_with_index(plan)

    assert [r["status"] for r in plan] == ["done", "pending", "pending"]


def test_resume_credits_only_the_surplus_index_entries(tmp_path, monkeypatch):
    """Two runs in the index, one of them already recorded in the plan: exactly
    one pending row is owed a credit, not two."""
    _install_fake_mode(monkeypatch, tmp_path)
    _write_index(tmp_path, 2)

    plan = _three_reps(status_of_rep1="done")
    campaign_mod._reconcile_with_index(plan)

    assert [r["status"] for r in plan] == ["done", "done", "pending"]


def test_resume_ignores_error_rows_when_counting_consumption(tmp_path, monkeypatch):
    """An 'error' row spent a run but produced no 'done' index entry, so it must
    not consume one either."""
    _install_fake_mode(monkeypatch, tmp_path)
    _write_index(tmp_path, 1)

    plan = _three_reps()
    plan[0]["status"] = "error"
    campaign_mod._reconcile_with_index(plan)

    assert [r["status"] for r in plan] == ["error", "done", "pending"]


# ---------------------------------------------------------------------------
# T16 (FR-14, FR-15) — contexts at the measured VRAM ceiling, and what
# does not fit is declared rather than filed as a failure
# ---------------------------------------------------------------------------

# Measured 2026-08-22, cell by cell, with prefill throughput as the witness (a
# context past the ceiling does not fail to load: the Windows driver spills the
# KV cache to system memory and prefill collapses -- Ministral 2,344 -> 82.8 t/s
# at 43,008, granite 2,176 -> 53.9 t/s at 32,768). Frozen here so a future edit
# has to argue with a measurement instead of a guess.
CTX_CEILING = {
    "qwen3.5-9b-nothink": 51200,
    "qwen3.5-9b-think": 51200,
    "ministral-3-8b": 38912,
    "granite-4.1-8b": 28672,   # no headroom at all on an 8 GB card
    "gemma-4-12b": 43008,
    "phi4-mini": 43008,
}


def test_cells_declare_the_measured_context_ceiling():
    for cell in campaign_mod._load_cells():
        assert cell["ctx_size"] == CTX_CEILING[cell["cell"]], (
            f"{cell['cell']} declares ctx_size={cell['ctx_size']}, "
            f"measured ceiling is {CTX_CEILING[cell['cell']]}"
        )


def test_modes_json_agrees_with_the_raised_contexts():
    """T12 already ties modes.json to campaign-cells.json; this pins the values
    themselves, because the two files were raised in one edit and a half-applied
    change would leave the server started at one context and the record labelled
    with another."""
    by_mode = _modes_by_name(MODES_PATH)
    for cell in campaign_mod._load_cells():
        for name in cell["modes"]:
            assert by_mode[name]["ctx_size"] == CTX_CEILING[cell["cell"]]


def test_window_overflow_is_recognised():
    raw = ('OpenAI-compatible API error 400: {"error":{"code":400,"message":'
           '"request (37487 tokens) exceeds the available context size (31744 tokens), '
           'try increasing it"}}')
    assert campaign_mod._is_window_overflow(raw) is True
    assert campaign_mod._is_window_overflow("connection reset by peer") is False
    assert campaign_mod._is_window_overflow(None) is False
    assert campaign_mod._is_window_overflow("") is False


def test_protocol_records_the_cell_set_and_context_amendment():
    text = PROTOCOL_PATH.read_text(encoding="utf-8")
    amendments = text.split("## 12. Amendments", 1)[1]
    rows = [ln for ln in amendments.splitlines() if ln.startswith("| 2026-08-22")]
    assert any("5.3" in r and "51,200" in r for r in rows), \
        "no 2026-08-22 amendment row covering SS5.3 and the raised contexts"

    section = text.split("### 5.3", 1)[1].split("### 5.4", 1)[0]
    for cell in ("granite", "gemma", "Ministral", "Phi-4-mini", "Qwen"):
        assert cell in section, f"SS5.3 does not mention {cell}"
    assert "skipped-window" in section


# ---------------------------------------------------------------------------
# T17 (FR-16) — a run whose answer cannot fit is refused before it is spent
# ---------------------------------------------------------------------------

def test_min_generation_room_is_declared():
    assert campaign_mod.MIN_GENERATION_ROOM == 2048


def test_row_with_no_room_left_is_skipped_without_spending_a_run(monkeypatch):
    """Measured 2026-08-22 on queue-07 at L4: gemma's prompt is 42,960 tokens in
    a 43,008 window and the model answered in 48 tokens; Ministral was cut off at
    the 1,425 that were left. Both reported 'done' and entered the results as
    measurements of the model. They measured the bench."""
    monkeypatch.setattr(campaign_mod, "_mode_config", lambda mode: {"model": "m"})
    monkeypatch.setattr(campaign_mod, "_load_input", lambda *a, **k: object())
    monkeypatch.setattr(campaign_mod, "_window_room", lambda *a, **k: (42960, 48))
    invoked = []
    monkeypatch.setattr(campaign_mod, "_invoke_api", lambda *a, **k: invoked.append(a))

    row = {"cell": "c1", "mode": "m1", "rendering": "L4", "queue": "queue-07", "rep": 1,
           "status": "pending"}
    out = campaign_mod._execute_row(row, {"cell": "c1", "runner_type": "api", "ctx_size": 43008}, "m1", "L4",
                                    "queue-07", None, {}, {}, {})

    assert out is None
    assert row["status"] == "skipped-window"
    assert invoked == [], "the run was spent even though its answer could not fit"


def test_row_with_room_proceeds(monkeypatch):
    monkeypatch.setattr(campaign_mod, "_mode_config", lambda mode: {"model": "m"})
    monkeypatch.setattr(campaign_mod, "_load_input", lambda *a, **k: object())
    monkeypatch.setattr(campaign_mod, "_window_room", lambda *a, **k: (35979, 7029))
    monkeypatch.setattr(campaign_mod, "_stage", lambda b: (_ for _ in ()).throw(RuntimeError("proceeded")))

    row = {"cell": "c1", "mode": "m1", "rendering": "L4", "queue": "queue-07", "rep": 1,
           "status": "pending"}
    with pytest.raises(RuntimeError, match="proceeded"):
        campaign_mod._execute_row(row, {"cell": "c1", "runner_type": "api", "ctx_size": 43008}, "m1", "L4",
                                  "queue-07", None, {}, {}, {})


def test_unmeasurable_window_does_not_skip_the_row(monkeypatch):
    """/tokenize unavailable is not evidence that the row does not fit: the run
    proceeds as before rather than being dropped on a failed measurement."""
    monkeypatch.setattr(campaign_mod, "_mode_config", lambda mode: {"model": "m"})
    monkeypatch.setattr(campaign_mod, "_load_input", lambda *a, **k: object())
    monkeypatch.setattr(campaign_mod, "_window_room", lambda *a, **k: (None, None))
    monkeypatch.setattr(campaign_mod, "_stage", lambda b: (_ for _ in ()).throw(RuntimeError("proceeded")))

    row = {"cell": "c1", "mode": "m1", "rendering": "L4", "queue": "queue-07", "rep": 1,
           "status": "pending"}
    with pytest.raises(RuntimeError, match="proceeded"):
        campaign_mod._execute_row(row, {"cell": "c1", "runner_type": "api", "ctx_size": 43008}, "m1", "L4",
                                  "queue-07", None, {}, {}, {})


def test_a_plan_that_predates_the_cells_file_is_refused(monkeypatch, capsys):
    """_run_cell reports an unknown cell and an exhausted one the same way -- "no
    pending rows -- skipping". A plan built before the cells were renamed would
    print that for every cell and close with "all cells processed": a campaign that
    ran nothing, indistinguishable from one that finished. Reordering the cells to
    put the thinking mode last (2026-08-23) is exactly when this bites."""
    stale = [{"cell": "qwen3.5-9b", "mode": "llama-qwen3.5-9b-think",
              "rendering": "L0", "queue": "queue-01", "rep": 1, "status": "pending"}]
    monkeypatch.setattr(campaign_mod, "_load_cells",
                        lambda path=None: [{"cell": "qwen3.5-9b-nothink"}, {"cell": "qwen3.5-9b-think"}])

    with pytest.raises(SystemExit) as exc:
        campaign_mod._assert_plan_is_runnable(stale)

    msg = str(exc.value)
    assert "qwen3.5-9b-nothink" in msg and "qwen3.5-9b-think" in msg
    assert "campaign.py plan" in msg


def test_a_plan_matching_the_cells_file_passes():
    rows = [{"cell": c["cell"], "status": "pending"} for c in campaign_mod._load_cells()]
    campaign_mod._assert_plan_is_runnable(rows)      # must not raise


def test_the_thinking_mode_runs_last():
    """qwen3.5-9b in thinking mode spent its whole 13,024-token budget deliberating
    on all five of MAIN's first rows and never began the answer (stop_reason
    'length', 36-52 KB of reasoning, no payload). Its 210 rows are worth roughly
    fourteen hours; putting them at the end means the five models that do answer
    are measured first, and the decision on this one can be taken with their
    results already in hand."""
    cells = campaign_mod._load_cells()
    thinking = [i for i, c in enumerate(cells)
                if any("think" in m and "nothink" not in m for m in c["modes"])]

    assert thinking == [len(cells) - 1], "the thinking mode is not the last cell"


def test_every_mode_still_runs_exactly_once():
    """Splitting a cell in two is a reordering, not a change of scope."""
    modes = [m for c in campaign_mod._load_cells() for m in c["modes"]]
    assert len(modes) == len(set(modes)) == 6


def test_two_modes_on_the_same_gguf_do_not_share_a_resume_coordinate():
    """llama-qwen3.5-9b-think and -nothink are the same gguf, the same backend and
    the same reasoning_budget of 12000. Only `thinking` separates them, and it was
    in neither key -- so seven think runs satisfied nothink's coordinates too and a
    resume marked five nothink rows done that had never run. A row the plan calls
    done is a row nobody looks at again: runs that silently never happen are the
    worst kind of missing data."""
    think   = campaign_mod._index_key_for("llama-qwen3.5-9b-think",   "L0", "queue-01")
    nothink = campaign_mod._index_key_for("llama-qwen3.5-9b-nothink", "L0", "queue-01")

    assert think != nothink


def test_the_resume_credits_a_run_to_the_mode_that_produced_it(tmp_path, monkeypatch):
    rows = [{"fixture_id": campaign_mod.SUPPORT_INTAKE_FIXTURE_ID,
             "staged_input_id": "queue-01", "context": "E0",
             "model_id": "ai-models/Qwen3.5-9B-Q4_K_M.gguf", "spec_version": "0.6",
             "backend": "openai", "reasoning_budget": 12000,
             "process_rendering": "L0", "mode": "llama-qwen3.5-9b-think",
             "status": "done"}]
    index = tmp_path / "index.jsonl"
    index.write_text("\n".join(json.dumps(r) for r in rows) + "\n", encoding="utf-8")
    monkeypatch.setattr(campaign_mod, "INDEX_PATH", index)

    plan = [{"cell": "qwen3.5-9b-nothink", "mode": "llama-qwen3.5-9b-nothink",
             "rendering": "L0", "queue": "queue-01", "rep": 1, "status": "pending"},
            {"cell": "qwen3.5-9b-think", "mode": "llama-qwen3.5-9b-think",
             "rendering": "L0", "queue": "queue-01", "rep": 1, "status": "pending"}]
    campaign_mod._reconcile_with_index(plan)

    assert [r["status"] for r in plan] == ["pending", "done"]


# ---------------------------------------------------------------------------
# `plan` does not destroy a campaign in progress (2026-08-23)
# ---------------------------------------------------------------------------

def test_plan_refuses_to_rebuild_over_rows_that_already_ran(tmp_path, monkeypatch, capsys):
    """It reads like an inspection command and is not one: it rebuilds from the
    cell table and writes. Run against MAIN at 421 done, 3 error and 3
    skipped-window, it left 1260 pending. The done rows would come back from
    index.jsonl on the next resume; `error` and `skipped-window` would not, having
    no index row to be credited from -- and a `skipped-window` row buys the same
    refusal again, its prompt being larger than the model's window."""
    plan_path = tmp_path / "campaign-plan.json"
    rows = [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "q1", "rep": 1,
             "status": s} for s in ("done", "error", "skipped-window", "pending")]
    plan_path.write_text(json.dumps(rows), encoding="utf-8")

    monkeypatch.setattr(campaign_mod, "PLAN_PATH", plan_path)
    monkeypatch.setattr(campaign_mod, "_use_results_root", lambda *a, **k: None)

    with pytest.raises(SystemExit) as exc:
        campaign_mod.cmd_plan(argparse.Namespace(force=False))

    assert "3 rows already run" in str(exc.value)
    assert json.loads(plan_path.read_text(encoding="utf-8")) == rows   # untouched


def test_plan_rebuilds_freely_when_nothing_has_run(tmp_path, monkeypatch):
    plan_path = tmp_path / "campaign-plan.json"
    plan_path.write_text(json.dumps(
        [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "q1", "rep": 1,
          "status": "pending"}]), encoding="utf-8")

    monkeypatch.setattr(campaign_mod, "PLAN_PATH", plan_path)
    monkeypatch.setattr(campaign_mod, "_use_results_root", lambda *a, **k: None)
    monkeypatch.setattr(campaign_mod, "build_plan", lambda *a: [{"status": "pending"}])
    saved = []
    monkeypatch.setattr(campaign_mod, "_save_plan", lambda r: saved.append(r))

    campaign_mod.cmd_plan(argparse.Namespace(force=False))
    assert saved == [[{"status": "pending"}]]


def test_force_rebuilds_over_a_started_plan(tmp_path, monkeypatch):
    """The guard is on the file, not on the command: rebuilding is legitimate."""
    plan_path = tmp_path / "campaign-plan.json"
    plan_path.write_text(json.dumps(
        [{"cell": "c1", "mode": "m1", "rendering": "L0", "queue": "q1", "rep": 1,
          "status": "done"}]), encoding="utf-8")

    monkeypatch.setattr(campaign_mod, "PLAN_PATH", plan_path)
    monkeypatch.setattr(campaign_mod, "_use_results_root", lambda *a, **k: None)
    monkeypatch.setattr(campaign_mod, "build_plan", lambda *a: [{"status": "pending"}])
    saved = []
    monkeypatch.setattr(campaign_mod, "_save_plan", lambda r: saved.append(r))

    campaign_mod.cmd_plan(argparse.Namespace(force=True))
    assert saved == [[{"status": "pending"}]]
