#!/usr/bin/env python3
"""
Build the `prose-mechanical` documents of the minimum-context experiment.

doc/experiment-minimum-context.md SS5.4 declares two prose renderings of the same SOL
document. `prose-generated` is a model reading the SOL script under a frozen prompt
(tests/fixtures/PROSE-VARIANT-PROMPT.md); `prose-mechanical` is the deterministic
renderer that ships with the skill, .claude/skills/sol/scripts/sol2prose.py.

This script is the second one's generator, and it is a frozen artefact in the sense of
SS8.1: a defect in a `prose-mechanical` document is fixed HERE and the documents are
regenerated. Hand-patching one would make the cell measure a document nobody can
reproduce.

What it produces, per fixture, is the fixture itself with ONLY its process section
swapped:

    <frontmatter and every material section, byte for byte>
    ## The procedure          <- was '## SOL script'
    <sol2prose's rendering>

Swapping the *section* rather than cutting at the heading matters: in cart-total.md the
SOL script comes BEFORE '## File content', and cart-total-prose-generated.md keeps that
order. Both prose variants must differ from their SOL source in the process section and
nowhere else, or the comparison stops being between renderings and starts being between
documents.

One normalisation is applied to the fixture's own material, and one only: the sentence
that points at the process definition is re-pointed. Six of the seven fixtures open with
some form of "…by executing strictly the SOL script below", and below there is no longer
a SOL script -- the reference dangles, and it dangles at the top of the prompt, on the
sentence that tells the model what it is about to read. This is defect 4 of
tests/fixtures/PROSE-VARIANT-PROMPT.md, found there in five generations out of six and
fixed in that prompt; a generator that copies the material byte for byte reintroduces it,
so it is fixed here too. The rewrite is mechanical -- 'SOL script' becomes 'procedure
described', and 'execute' becomes 'follow' inside that same sentence -- and it is the
only place where the material is not carried across verbatim.

Three further normalisations are applied to sol2prose's output, and no others:

  1. its leading '# process' H1 is dropped -- the fixture already has an H1, and two H1s
     in one prompt is a shape the SOL document never has;
  2. its trailing '_Narrative rendering of ... generated by sol2prose.py..._' note is
     dropped -- it is a note ABOUT the generator, not part of the process, and the SOL
     document carries no equivalent;
  3. every heading left in it is demoted one level, so the renderer's '## What it does'
     and '## Subroutines' sit UNDER '## The procedure' instead of beside it. Without this
     they become siblings of '## File content' and the document says the subroutines are
     a section of the task rather than part of the process. Headings inside fenced code
     are left alone.

Everything else is quoted exactly as the renderer emitted it, including placeholders it
found in the source ('cat {{queue_path}}'), which the SOL prompt also carries
unsubstituted at E0.

The renderer is invoked as a SUBPROCESS, never imported: the skill's scripts are
deliberately self-contained with no cross-imports (doc/sol-convertibility.md
SS Portability guarantees), and importing one from here would quietly create the
dependency that guarantee denies.

Usage:
    python3 tests/scripts/build_prose_mechanical.py            # write the documents
    python3 tests/scripts/build_prose_mechanical.py --check    # verify, write nothing
"""

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures"
SOL2PROSE = REPO_ROOT / ".claude" / "skills" / "sol" / "scripts" / "sol2prose.py"

PROCESS_HEADING = "## SOL script"
PROSE_HEADING = "## The procedure"
RENDERING = "prose-mechanical"

# Markdown files under tests/fixtures/ that are not fixtures.
NOT_A_FIXTURE = {"README.md", "l2-glossary.md", "PROSE-VARIANT-PROMPT.md"}

_H1_RE = re.compile(r"\A#\s+process\s*\n+", re.IGNORECASE)
_FOOTNOTE_RE = re.compile(r"\n+---\n+_Narrative rendering of .*?_\s*\Z", re.DOTALL)
_FENCE_RE = re.compile(r"\A\s*(```|~~~)")
_HEADING_RE = re.compile(r"\A(#{1,5}) ")


def demote_headings(text: str) -> str:
    """Every ATX heading one level deeper, code fences untouched."""
    out, in_fence = [], False
    for line in text.split("\n"):
        if _FENCE_RE.match(line):
            in_fence = not in_fence
        elif not in_fence:
            line = _HEADING_RE.sub(lambda m: "#" + m.group(0), line)
        out.append(line)
    return "\n".join(out)


def fixture_paths() -> list[Path]:
    """Every SOL fixture document: has a '## SOL script' section, is not itself a
    rendering of one, and is not one of the directory's README/aux files."""
    out = []
    for path in sorted(FIXTURES_DIR.rglob("*.md")):
        if path.name in NOT_A_FIXTURE or "-prose-" in path.name or path.suffixes[:1] == [".prose"]:
            continue
        if PROCESS_HEADING in path.read_text(encoding="utf-8"):
            out.append(path)
    return out


def render(fixture: Path) -> str:
    """sol2prose's rendering of the SOL fences in `fixture`, normalised."""
    proc = subprocess.run(
        [sys.executable, str(SOL2PROSE), str(fixture), "--stdout"],
        capture_output=True, text=True, encoding="utf-8",
    )
    if proc.returncode != 0:
        raise RuntimeError(f"sol2prose failed on {fixture.name}:\n{proc.stderr.strip()}")
    body = _H1_RE.sub("", proc.stdout.strip())
    body = _FOOTNOTE_RE.sub("", body)
    return demote_headings(body.strip()).strip()


_POINTER_RE = re.compile(r"[^.\n]*\bSOL script\b[^.\n]*")


def _repoint(match: re.Match) -> str:
    s = match.group(0).replace("SOL script", "procedure described")
    s = re.sub(r"\bExecute\b", "Follow", s)
    s = re.sub(r"\bexecuting\b", "following", s)
    s = re.sub(r"\bexecute\b", "follow", s)
    return s


def repoint_pointer_sentence(body: str) -> str:
    """'Execute strictly the SOL script below' -> 'Follow strictly the procedure
    described below'. Only sentences that name the SOL script are touched, and the
    frontmatter is never passed in: it must stay identical to the fixture's."""
    return _POINTER_RE.sub(_repoint, body)


def swap_process_section(fixture_text: str, prose: str) -> str:
    """Replace the '## SOL script' section -- heading through the next '## ' or EOF --
    with '## The procedure' and `prose`. Nothing outside that span is touched."""
    start = fixture_text.index(PROCESS_HEADING)
    rest = fixture_text[start + len(PROCESS_HEADING):]
    nxt = re.search(r"^## ", rest, re.MULTILINE)
    end = len(fixture_text) if nxt is None else start + len(PROCESS_HEADING) + nxt.start()
    tail = fixture_text[end:]
    return f"{fixture_text[:start]}{PROSE_HEADING}\n\n{prose}\n" + ("\n" + tail if tail else "")


def build(fixture: Path) -> tuple[Path, str]:
    out_path = fixture.with_name(f"{fixture.stem}-{RENDERING}.md")
    # Swap first, re-point second: before the swap the document still carries the
    # '## SOL script' heading, and re-pointing would rewrite the very heading the
    # swap looks for.
    text = swap_process_section(fixture.read_text(encoding="utf-8"), render(fixture))
    fm_match = re.match(r"\A(---\n.*?\n---\n)(.*)\Z", text, re.DOTALL)
    if fm_match:
        return out_path, fm_match.group(1) + repoint_pointer_sentence(fm_match.group(2))
    return out_path, repoint_pointer_sentence(text)


def main() -> int:
    check = "--check" in sys.argv[1:]
    fixtures = fixture_paths()
    if not fixtures:
        print("no fixtures found -- nothing to do", file=sys.stderr)
        return 1

    stale = []
    for fixture in fixtures:
        out_path, content = build(fixture)
        rel = out_path.relative_to(REPO_ROOT)
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else None
        if current == content:
            print(f"  unchanged  {rel}")
            continue
        if check:
            stale.append(rel)
            print(f"  STALE      {rel}")
            continue
        out_path.write_text(content, encoding="utf-8")
        print(f"  {'updated' if current is not None else 'written'}    {rel}")

    if check and stale:
        print(f"\n{len(stale)} document(s) do not match what this script produces. "
              f"Regenerate them -- do not edit them by hand (SS8.1).", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
